export const dummyHolders = [
  {
    username: "BTCFORLIFE",
    avgHold: "1d 20h avg. hold",
    positionValue: "$154,762.95",
    positionTokens: "2.1K SOL",
    pnlValue: "- $28,330.29",
    pnlPercent: "2.85%",
    isPnlPositive: false,
    avgEntryPrice: "$73.60",
    avgEntryMc: "$41.8B MC",
    thesis: "—",
    thesisLikes: 0,
    avatar: "https://i.pravatar.cc/150?u=BTCFORLIFE",
  },
  {
    username: "jpegxbt",
    avgHold: "12h 37m avg. hold",
    positionValue: "$72,829.62",
    positionTokens: "1K SOL",
    pnlValue: "- $37,006.64",
    pnlPercent: "30.95%",
    isPnlPositive: false,
    avgEntryPrice: "$108.94",
    avgEntryMc: "$61.9B MC",
    thesis: "big kols tweeting soon",
    thesisLikes: 16,
    avatar: "https://i.pravatar.cc/150?u=jpegxbt",
  },
  {
    username: "MereNovelQuokka",
    avgHold: "No hold time",
    positionValue: "$51,035.82",
    positionTokens: "701.80 SOL",
    pnlValue: "- $90,124.81",
    pnlPercent: "63.85%",
    isPnlPositive: false,
    avgEntryPrice: "$201.14",
    avgEntryMc: "$114.3B MC",
    thesis: "—",
    thesisLikes: 0,
    avatar: "https://i.pravatar.cc/150?u=MereNovelQuokka",
  },
  {
    username: "SolanaWhale",
    avgHold: "3d 4h avg. hold",
    positionValue: "$340,192.00",
    positionTokens: "4.5K SOL",
    pnlValue: "+ $45,210.50",
    pnlPercent: "15.32%",
    isPnlPositive: true,
    avgEntryPrice: "$65.20",
    avgEntryMc: "$38.1B MC",
    thesis: "accumulation zone before breakout",
    thesisLikes: 42,
    avatar: "https://i.pravatar.cc/150?u=SolanaWhale",
  },
  {
    username: "CryptoNinja",
    avgHold: "5h 12m avg. hold",
    positionValue: "$12,450.00",
    positionTokens: "150 SOL",
    pnlValue: "+ $1,240.00",
    pnlPercent: "11.05%",
    isPnlPositive: true,
    avgEntryPrice: "$74.10",
    avgEntryMc: "$42.1B MC",
    thesis: "—",
    thesisLikes: 0,
    avatar: "https://i.pravatar.cc/150?u=CryptoNinja",
  },
  {
    username: "DeFiDegen",
    avgHold: "1w 2d avg. hold",
    positionValue: "$85,230.15",
    positionTokens: "1.1K SOL",
    pnlValue: "- $12,500.00",
    pnlPercent: "12.80%",
    isPnlPositive: false,
    avgEntryPrice: "$89.50",
    avgEntryMc: "$50.8B MC",
    thesis: "long term hold, ignoring short term noise",
    thesisLikes: 105,
    avatar: "https://i.pravatar.cc/150?u=DeFiDegen",
  },
  {
    username: "ApexTrader",
    avgHold: "45m avg. hold",
    positionValue: "$5,120.00",
    positionTokens: "70 SOL",
    pnlValue: "- $450.00",
    pnlPercent: "8.07%",
    isPnlPositive: false,
    avgEntryPrice: "$79.60",
    avgEntryMc: "$45.2B MC",
    thesis: "—",
    thesisLikes: 0,
    avatar: "https://i.pravatar.cc/150?u=ApexTrader",
  },
  {
    username: "MoonWalker",
    avgHold: "2d 15h avg. hold",
    positionValue: "$215,800.50",
    positionTokens: "2.8K SOL",
    pnlValue: "+ $68,900.20",
    pnlPercent: "46.90%",
    isPnlPositive: true,
    avgEntryPrice: "$52.40",
    avgEntryMc: "$29.8B MC",
    thesis: "ecosystem growth is accelerating",
    thesisLikes: 210,
    avatar: "https://i.pravatar.cc/150?u=MoonWalker",
  },
  {
    username: "SwingKing",
    avgHold: "1d 2h avg. hold",
    positionValue: "$45,670.80",
    positionTokens: "610 SOL",
    pnlValue: "+ $4,120.50",
    pnlPercent: "9.91%",
    isPnlPositive: true,
    avgEntryPrice: "$68.10",
    avgEntryMc: "$38.7B MC",
    thesis: "—",
    thesisLikes: 0,
    avatar: "https://i.pravatar.cc/150?u=SwingKing",
  },
];

export const dummySwaps = [
  {
    username: "yessire",
    action: "Sell",
    amount: "$190.89",
    price: "$72.25",
    time: "2h",
    avatar: "https://i.pravatar.cc/150?u=yessire",
  },
  {
    username: "mothers",
    action: "Sell",
    amount: "$2.86",
    price: "$72.31",
    time: "2h",
    avatar: "https://i.pravatar.cc/150?u=mothers",
  },
  {
    username: "michual",
    action: "Sell",
    amount: "$5.10",
    price: "$72.33",
    time: "2h",
    avatar: "https://i.pravatar.cc/150?u=michual",
  },
  {
    username: "PhantomCap",
    action: "Sell",
    amount: "$2.03",
    price: "$72.30",
    time: "2h",
    avatar: "https://i.pravatar.cc/150?u=PhantomCap",
  },
  {
    username: "DegenTrader",
    action: "Buy",
    amount: "$1,450.00",
    price: "$71.80",
    time: "3h",
    avatar: "https://i.pravatar.cc/150?u=DegenTrader",
  },
  {
    username: "SolanaWhale",
    action: "Buy",
    amount: "$50,200.00",
    price: "$71.50",
    time: "4h",
    avatar: "https://i.pravatar.cc/150?u=SolanaWhale",
  },
];

export const dummyThesis = [
  {
    username: "blqsqr",
    avatar: "https://i.pravatar.cc/150?u=blqsqr",
    time: "6h",
    tokenAmount: "$8.25",
    pnl: "+$0.91",
    isPnlPositive: true,
    text: "solana is home and I'm prepared for a solana summer the same as in Paris 2026",
    likes: 0,
    older: 4,
  },
  {
    username: "CPTPrice",
    avatar: "https://i.pravatar.cc/150?u=CPTPrice",
    time: "11h",
    tokenAmount: "$67,017.68",
    pnl: "+$2,033.85",
    isPnlPositive: true,
    text: "$sol is still the home for memes, onboarding millions, but that's just the start. perps, defi, consumer apps, rwas, tokenized assets, and better tokenomics make $600+ this cycle. builders never stop..",
    likes: 1,
    older: 16,
  },
];
